-- Script DDL generado desde los mapeos JPA del proyecto
-- Asegúrate de revisar los nombres de tabla/columna en tu esquema SQL Server.

IF OBJECT_ID('dbo.USUARIOS', 'U') IS NULL
CREATE TABLE dbo.USUARIOS (
    USUARIO_ID NVARCHAR(255) NOT NULL PRIMARY KEY,
    NOMBRE NVARCHAR(255) NOT NULL,
    CORREO NVARCHAR(255),
    CONTRASENA NVARCHAR(255),
    TELEFONO NVARCHAR(255)
);

IF OBJECT_ID('dbo.PROYECTOS', 'U') IS NULL
CREATE TABLE dbo.PROYECTOS (
    PROYECTO_ID NVARCHAR(255) NOT NULL PRIMARY KEY,
    NOMBRE NVARCHAR(255) NOT NULL,
    CORREO NVARCHAR(255),
    TIPO NVARCHAR(255),
    DESCRIPCION NVARCHAR(255),
    FECHA_INICIO NVARCHAR(255) NOT NULL,
    FECHA_FIN NVARCHAR(255),
    ESTADO NVARCHAR(255) NOT NULL
);

IF OBJECT_ID('dbo.PARTICIPANTES', 'U') IS NULL
CREATE TABLE dbo.PARTICIPANTES (
    PARTICIPANTE_ID NVARCHAR(255) NOT NULL PRIMARY KEY,
    NOMBRE NVARCHAR(255) NOT NULL,
    CORREO NVARCHAR(255),
    UBICACION NVARCHAR(255) NOT NULL,
    ROL NVARCHAR(255) NOT NULL
);

IF OBJECT_ID('dbo.PATROCINIO', 'U') IS NULL
CREATE TABLE dbo.PATROCINIO (
    PATROCINADOR_ID NVARCHAR(255) NOT NULL PRIMARY KEY,
    NOMBRE NVARCHAR(255) NOT NULL,
    CORREO NVARCHAR(255),
    CONTACTO NVARCHAR(255) NOT NULL,
    TIPO NVARCHAR(255),
    APORTE NVARCHAR(255)
);

IF OBJECT_ID('dbo.RECURSOS', 'U') IS NULL
CREATE TABLE dbo.RECURSOS (
    RECURSO_ID NVARCHAR(255) NOT NULL PRIMARY KEY,
    NOMBRE NVARCHAR(255) NOT NULL,
    CATEGORIA NVARCHAR(255) NOT NULL,
    ESTADO NVARCHAR(255) NOT NULL,
    UBICACION NVARCHAR(255) NOT NULL,
    FECHA_INGRESO NVARCHAR(255),
    PROYECTO_ID NVARCHAR(255)
);

IF OBJECT_ID('dbo.MANTENIMIENTO_RECURSOS', 'U') IS NULL
CREATE TABLE dbo.MANTENIMIENTO_RECURSOS (
    MMTO_ID NVARCHAR(255) NOT NULL PRIMARY KEY,
    NOMBRE_TECNICO NVARCHAR(255) NOT NULL,
    DESCRIPCION NVARCHAR(255) NOT NULL,
    ESTADO NVARCHAR(255) NOT NULL,
    CATEGORIA NVARCHAR(255) NOT NULL,
    FECHA NVARCHAR(255),
    RECURSO_ID NVARCHAR(255)
);
